#version 450
layout(local_size_x = 32, local_size_y = 1) in;

// 即使 CPU 傳入 uint16 (half)，我們在 Shader 中宣告為 float 進行測試 (Vulkan 會自動映射)
layout(std430, binding = 0) readonly buffer InputA { float data[]; } bufS;
layout(std430, binding = 1) writeonly buffer OutputC { float data[]; } bufOut;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < 1024) {
        bufOut.data[idx] = bufS.data[idx] + 1.0;
    }
}
